### ISSUE TITLE
Bug when testing: "WFLYLNCHR0001: The path 'null' does not exist"

### ISSUE THREAD

**Issue by ogregoire** [javaeekickoff/java-ee-kickoff-app#22]
I'm launching the tests using the following command:

    mvn verify -P wildfly

The Maven result is the following:

    Tests in error:
      org.example.kickoff.business.EntityServiceTest: Could not start container
      org.example.kickoff.business.UserServiceTest: Arquillian initialization has already been attempted, but failed. See previous exceptions for cause

And the stack trace is the following:

    Running org.example.kickoff.business.EntityServiceTest
    Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.713 sec <<< FAILURE!
    org.example.kickoff.business.EntityServiceTest  Time elapsed: 1.713 sec  <<< ERROR!
    org.jboss.arquillian.container.spi.client.container.LifecycleException: Could not start container
            at org.jboss.as.arquillian.container.managed.ManagedDeployableContainer.startInternal(ManagedDeployableContainer.java:168)
            at org.jboss.as.arquillian.container.CommonDeployableContainer.start(CommonDeployableContainer.java:123)
            at org.jboss.arquillian.container.impl.ContainerImpl.start(ContainerImpl.java:179)
            at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:137)
            at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:133)
            at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forContainer(ContainerLifecycleController.java:208)
            at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.startContainer(ContainerLifecycleController.java:133)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
            at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
            at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
            at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:54)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
            at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
            at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
            at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
            at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
            at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$2.perform(ContainerLifecycleController.java:70)
            at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$2.perform(ContainerLifecycleController.java:64)
            at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forEachSuiteContainer(ContainerLifecycleController.java:181)
            at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.startSuiteContainers(ContainerLifecycleController.java:64)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
            at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
            at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
            at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
            at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
            at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
            at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:83)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
            at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
            at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
            at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
            at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
            at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
            at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
            at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:70)
            at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:111)
            at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
            at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
            at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
            at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
            at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
            at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
            at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
    Caused by: java.lang.IllegalArgumentException: WFLYLNCHR0001: The path 'null' does not exist
            at org.wildfly.core.launcher.Environment.validateWildFlyDir(Environment.java:313)
            at org.wildfly.core.launcher.AbstractCommandBuilder.validateWildFlyDir(AbstractCommandBuilder.java:652)
            at org.wildfly.core.launcher.StandaloneCommandBuilder.of(StandaloneCommandBuilder.java:91)
            at org.jboss.as.arquillian.container.managed.ManagedDeployableContainer.startInternal(ManagedDeployableContainer.java:86)
            ... 68 more

**Comment by BalusC** [comment]
Test cases have been caught up.
