### ISSUE TITLE
OmniSecurity on WildFly 8.2 ?

### ISSUE THREAD

**Issue by JensPiegsa** [javaeekickoff/java-ee-kickoff-app#3]
Hi Arjan,

I'd love to see that working on WildFly 8.2. Currently I'm stuck on a generic:

```
Caused by: javax.servlet.ServletException: UT010032: Authenticationfailed
  at io.undertow.servlet.spec.HttpServletRequestImpl.authenticate(HttpServletRequestImpl.java:416) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at javax.servlet.http.HttpServletRequestWrapper.authenticate(HttpServletRequestWrapper.java:338) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
  at org.omnifaces.security.jaspic.core.Jaspic.authenticate(Jaspic.java:84) [omnifaces-security-0.6-ALPHA.jar:0.6-ALPHA]
```

It seems like the custom server auth module hasn't come to action yet. Any hints?

Regards,
Jens

**Comment by arjantijms** [comment]
Possibly caused by the fact that JASPIC needs to be activated on JBoss EAP 7 (alpha/beta) and WildFly (at least up till 10rc4). See http://arjan-tijms.omnifaces.org/2015/08/activating-jaspic-in-jboss-wildfly.html

This is a major issue that has been causing problems for a long time, but may now finally going to be addressed in WildFly 10rc5.

**Comment by BalusC** [comment]
Kickoff App is currently designed for WF 10+
