### ISSUE TITLE
Error while trying to deploy on wildfly 10.1 =>  Circular dependency installing java:app/kickoff/DataSource

### ISSUE THREAD

**Issue by samyomar** [javaeekickoff/java-ee-kickoff-app#8]
I got thi error trying to deploy on wildfly 10.1 from netbeans or from maven.

```
Caused by: java.lang.IllegalArgumentException: WFLYEE0037: Circular dependency installing java:app/kickoff/DataSource
	at org.jboss.as.ee.component.deployers.ModuleJndiBindingProcessor.addJndiBinding(ModuleJndiBindingProcessor.java:222)
	at org.jboss.as.ee.component.deployers.ModuleJndiBindingProcessor.deploy(ModuleJndiBindingProcessor.java:107)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	... 5 more
```
```

**Comment by BalusC** [comment]
Not reproducible.
